import type { Category } from "../hooks/useDynamicPreferences";
import type { ParsedPreference } from "../services/parser";
import { userChromeOptions, userContentOptions } from "../data/cssOptions";

export function generateUserJs(
  categories: Category[],
  selections: Record<string, boolean>,
  customValues: Record<string, boolean | number | string> = {}
): string {
  const allPrefs: (ParsedPreference & { categoryName: string })[] = [];
  
  categories.forEach((cat) => {
    cat.preferences.forEach((p) => {
      if (selections[p.key]) {
        // Use custom value if available, otherwise use default
        const value = customValues[p.key] !== undefined ? customValues[p.key] : p.value;
        allPrefs.push({ ...p, value, categoryName: cat.name });
      }
    });
  });

  if (allPrefs.length === 0) return "";

  let output = `/****************************************************************************
 * user.js - Generated by Firefox user.js Generator
 * 
 * Generated: ${new Date().toISOString().split("T")[0]}
 * Selected preferences: ${allPrefs.length}
 *
 * Sources:
 * - https://github.com/yokoffing/Betterfox
 * - https://github.com/arkenfox/user.js
 *
 * Instructions:
 * 1. Open Firefox and type about:profiles in the URL bar
 * 2. Find your profile and click "Open Folder" in Root Directory
 * 3. Place this file as "user.js" in that folder
 * 4. Restart Firefox
 ****************************************************************************/

`;

  // Group by category
  const grouped = new Map<string, typeof allPrefs>();
  allPrefs.forEach((pref) => {
    if (!grouped.has(pref.categoryName)) grouped.set(pref.categoryName, []);
    grouped.get(pref.categoryName)!.push(pref);
  });

  grouped.forEach((prefs, catName) => {
    output += `\n${"/".repeat(76)}\n`;
    output += ` * SECTION: ${catName.toUpperCase()}\n`;
    output += `${"/".repeat(76)}\n\n`;

    prefs.forEach((pref) => {
      output += `// ${pref.description}\n`;
      output += `// Source: ${pref.source}\n`;
      if (pref.warnings.length > 0) {
        output += `// ⚠️ WARNING: ${pref.warnings.join("; ")}\n`;
      }
      const value =
        typeof pref.value === "string"
          ? `"${pref.value}"`
          : String(pref.value);
      output += `user_pref("${pref.key}", ${value});\n\n`;
    });
  });

  output += `\n${"/".repeat(76)}\n`;
  output += ` * END: user.js\n`;
  output += `${"/".repeat(76)}\n`;

  return output;
}

export function generateUserChrome(selections: Record<string, boolean>): string {
  const selected = userChromeOptions.filter((o) => selections[o.id]);
  if (selected.length === 0) return "";

  let output = `/*
 * userChrome.css - Generated by Firefox user.js Generator
 * 
 * Generated: ${new Date().toISOString().split("T")[0]}
 * Selected options: ${selected.length}
 *
 * Instructions:
 * 1. Enable toolkit.legacyUserProfileCustomizations.stylesheets in about:config
 * 2. Open about:profiles and find your profile Root Directory
 * 3. Create a "chrome" folder if it doesn't exist
 * 4. Place this file as "userChrome.css" inside the chrome folder
 * 5. Restart Firefox
 */

`;

  selected.forEach((option) => {
    output += `/* ${option.name} - ${option.description} */\n`;
    if (option.risk === "medium") {
      output += `/* ⚡ NOTE: Medium risk - may cause some UI issues */\n`;
    }
    output += `${option.css}\n\n`;
  });

  return output;
}

export function generateUserContent(selections: Record<string, boolean>): string {
  const selected = userContentOptions.filter((o) => selections[o.id]);
  if (selected.length === 0) return "";

  let output = `/*
 * userContent.css - Generated by Firefox user.js Generator
 * 
 * Generated: ${new Date().toISOString().split("T")[0]}
 * Selected options: ${selected.length}
 *
 * Instructions:
 * 1. Enable toolkit.legacyUserProfileCustomizations.stylesheets in about:config
 * 2. Open about:profiles and find your profile Root Directory
 * 3. Create a "chrome" folder if it doesn't exist
 * 4. Place this file as "userContent.css" inside the chrome folder
 * 5. Restart Firefox
 */

`;

  selected.forEach((option) => {
    output += `/* ${option.name} - ${option.description} */\n`;
    if (option.risk === "medium") {
      output += `/* ⚡ NOTE: Medium risk - may affect website appearance */\n`;
    }
    output += `${option.css}\n\n`;
  });

  return output;
}

export function getPreferenceCount(selections: Record<string, boolean>): number {
  return Object.values(selections).filter(Boolean).length;
}
