import { useState, useMemo, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Zap, Shield, EyeOff, Sparkles, Lock, ShieldCheck,
  Download, Copy, Check, RotateCcw, ChevronRight,
  Settings, Info, AlertTriangle, Github, Moon
} from 'lucide-react';
import { categories, presets, type Preference, type PresetType } from './data/preferences';

const iconMap: Record<string, any> = {
  Zap, Shield, EyeOff, Sparkles, Lock, ShieldCheck,
};

function App() {
  const [activeTab, setActiveTab] = useState(categories[0].id);
  const [selections, setSelections] = useState<Record<string, boolean>>(presets.balanced.selections);
  const [copied, setCopied] = useState(false);
  const [showPreview, setShowPreview] = useState(false);
  const [expandedPrefs, setExpandedPrefs] = useState<Set<string>>(new Set());
  const [searchQuery, setSearchQuery] = useState('');

  const activeCategory = categories.find(c => c.id === activeTab)!;

  const selectedCount = useMemo(() =>
    Object.values(selections).filter(Boolean).length,
    [selections]
  );

  const totalCount = useMemo(() =>
    categories.reduce((acc, cat) => acc + cat.preferences.length, 0),
    []
  );

  const togglePreference = useCallback((id: string) => {
    setSelections(prev => ({ ...prev, [id]: !prev[id] }));
  }, []);

  const toggleExpand = useCallback((id: string) => {
    setExpandedPrefs(prev => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }, []);

  const applyPreset = useCallback((preset: PresetType) => {
    setSelections({ ...presets[preset].selections });
  }, []);

  const resetAll = useCallback(() => {
    setSelections({});
  }, []);

  const selectAll = useCallback(() => {
    const all: Record<string, boolean> = {};
    categories.forEach(cat => {
      cat.preferences.forEach(pref => {
        all[pref.id] = true;
      });
    });
    setSelections(all);
  }, []);

  const generateUserJs = useCallback(() => {
    let output = `/****************************************************************************
 * user.js - Generated by Firefox user.js Generator
 * Based on Betterfox & arkenfox/user.js
 * 
 * Generated: ${new Date().toISOString().split('T')[0]}
 * Selected preferences: ${selectedCount}/${totalCount}
 *
 * Sources:
 * - https://github.com/yokoffing/Betterfox
 * - https://github.com/arkenfox/user.js
 ****************************************************************************/

`;

    categories.forEach(category => {
      const selectedPrefs = category.preferences.filter(p => selections[p.id]);
      if (selectedPrefs.length === 0) return;

      output += `\n${'/'.repeat(76)}\n`;
      output += ` * SECTION: ${category.name.toUpperCase()}\n`;
      output += `${'/'.repeat(76)}\n\n`;

      selectedPrefs.forEach(pref => {
        output += `// ${pref.description}\n`;
        output += `// Source: ${pref.source === 'both' ? 'Betterfox + arkenfox' : pref.source === 'betterfox' ? 'Betterfox' : 'arkenfox'}\n`;
        if (pref.risk === 'high') {
          output += `// ⚠️ WARNING: High risk - may cause significant site breakage\n`;
        } else if (pref.risk === 'medium') {
          output += `// ⚡ NOTE: Medium risk - may cause some site issues\n`;
        }
        const value = typeof pref.defaultValue === 'string'
          ? `"${pref.defaultValue}"`
          : String(pref.defaultValue);
        output += `user_pref("${pref.key}", ${value});\n\n`;
      });
    });

    output += `\n${'/'.repeat(76)}\n`;
    output += ` * END: user.js\n`;
    output += `${'/'.repeat(76)}\n`;

    return output;
  }, [selections, selectedCount, totalCount]);

  const copyToClipboard = useCallback(() => {
    navigator.clipboard.writeText(generateUserJs());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [generateUserJs]);

  const downloadFile = useCallback(() => {
    const blob = new Blob([generateUserJs()], { type: 'text/javascript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'user.js';
    a.click();
    URL.revokeObjectURL(url);
  }, [generateUserJs]);

  const filteredPreferences = useMemo(() => {
    if (!searchQuery.trim()) return activeCategory.preferences;
    const q = searchQuery.toLowerCase();
    return activeCategory.preferences.filter(p =>
      p.name.toLowerCase().includes(q) ||
      p.key.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q)
    );
  }, [activeCategory, searchQuery]);

  const getCategorySelectedCount = (catId: string) => {
    const cat = categories.find(c => c.id === catId);
    if (!cat) return 0;
    return cat.preferences.filter(p => selections[p.id]).length;
  };

  return (
    <div className="min-h-screen bg-[#1e1e2e] text-[#cdd6f4] font-sans">
      {/* Header */}
      <motion.header
        initial={{ y: -20, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        className="sticky top-0 z-50 backdrop-blur-xl bg-[#1e1e2e]/80 border-b border-[#313244]"
      >
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-[#cba6f7] to-[#f38ba8] flex items-center justify-center">
                <Settings className="w-5 h-5 text-[#1e1e2e]" />
              </div>
              <div>
                <h1 className="text-xl font-bold text-[#cdd6f4]">Firefox user.js Generator</h1>
                <p className="text-xs text-[#a6adc8]">Based on Betterfox & arkenfox</p>
              </div>
            </div>
            <div className="flex items-center gap-3">
              <div className="hidden sm:flex items-center gap-2 px-3 py-1.5 rounded-lg bg-[#313244] text-sm">
                <Moon className="w-4 h-4 text-[#cba6f7]" />
                <span className="text-[#a6adc8]">Catppuccin Mocha</span>
              </div>
              <a
                href="https://github.com"
                target="_blank"
                rel="noopener noreferrer"
                className="p-2 rounded-lg hover:bg-[#313244] transition-colors"
              >
                <Github className="w-5 h-5 text-[#a6adc8]" />
              </a>
            </div>
          </div>
        </div>
      </motion.header>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 py-6">
        {/* Stats Bar */}
        <motion.div
          initial={{ y: 10, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ delay: 0.1 }}
          className="flex flex-wrap items-center gap-3 mb-6"
        >
          <div className="flex items-center gap-2 px-4 py-2 rounded-xl bg-[#313244] border border-[#45475a]">
            <span className="text-[#a6adc8] text-sm">Selected:</span>
            <span className="text-[#a6e3a1] font-bold">{selectedCount}</span>
            <span className="text-[#6c7086]">/</span>
            <span className="text-[#a6adc8]">{totalCount}</span>
          </div>

          {/* Presets */}
          <div className="flex items-center gap-2 ml-auto">
            {(Object.entries(presets) as [PresetType, typeof presets.balanced][]).map(([key, preset]) => (
              <motion.button
                key={key}
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                onClick={() => applyPreset(key)}
                className="px-3 py-1.5 rounded-lg text-xs font-medium bg-[#313244] hover:bg-[#45475a] border border-[#45475a] transition-colors text-[#cdd6f4]"
                title={preset.description}
              >
                {preset.name}
              </motion.button>
            ))}
          </div>
        </motion.div>

        {/* Search */}
        <motion.div
          initial={{ y: 10, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ delay: 0.15 }}
          className="mb-6"
        >
          <input
            type="text"
            placeholder="Search preferences..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full px-4 py-3 rounded-xl bg-[#313244] border border-[#45475a] text-[#cdd6f4] placeholder-[#6c7086] focus:outline-none focus:border-[#cba6f7] focus:ring-1 focus:ring-[#cba6f7]/30 transition-all"
          />
        </motion.div>

        <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
          {/* Sidebar Tabs */}
          <motion.div
            initial={{ x: -20, opacity: 0 }}
            animate={{ x: 0, opacity: 1 }}
            transition={{ delay: 0.2 }}
            className="lg:col-span-1"
          >
            <div className="sticky top-24 space-y-2">
              {categories.map((category) => {
                const Icon = iconMap[category.icon] || Settings;
                const isActive = activeTab === category.id;
                const catSelected = getCategorySelectedCount(category.id);
                return (
                  <motion.button
                    key={category.id}
                    whileHover={{ x: 4 }}
                    whileTap={{ scale: 0.98 }}
                    onClick={() => { setActiveTab(category.id); setSearchQuery(''); }}
                    className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl text-left transition-all ${
                      isActive
                        ? 'bg-[#cba6f7]/10 border border-[#cba6f7]/30 text-[#cba6f7]'
                        : 'bg-[#313244]/50 border border-transparent hover:bg-[#313244] text-[#a6adc8]'
                    }`}
                  >
                    <Icon className="w-5 h-5 flex-shrink-0" />
                    <div className="flex-1 min-w-0">
                      <div className="text-sm font-medium truncate">{category.name}</div>
                      <div className="text-xs opacity-60">{catSelected}/{category.preferences.length} selected</div>
                    </div>
                    {isActive && <ChevronRight className="w-4 h-4" />}
                  </motion.button>
                );
              })}

              {/* Action Buttons */}
              <div className="pt-4 space-y-2">
                <motion.button
                  whileHover={{ scale: 1.02 }}
                  whileTap={{ scale: 0.98 }}
                  onClick={selectAll}
                  className="w-full flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl bg-[#a6e3a1]/10 border border-[#a6e3a1]/30 text-[#a6e3a1] text-sm font-medium transition-all"
                >
                  <Check className="w-4 h-4" />
                  Select All
                </motion.button>
                <motion.button
                  whileHover={{ scale: 1.02 }}
                  whileTap={{ scale: 0.98 }}
                  onClick={resetAll}
                  className="w-full flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl bg-[#f38ba8]/10 border border-[#f38ba8]/30 text-[#f38ba8] text-sm font-medium transition-all"
                >
                  <RotateCcw className="w-4 h-4" />
                  Reset All
                </motion.button>
              </div>
            </div>
          </motion.div>

          {/* Main Content */}
          <motion.div
            initial={{ y: 20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ delay: 0.3 }}
            className="lg:col-span-3"
          >
            {/* Category Header */}
            <div className="mb-6">
              <div className="flex items-center gap-3 mb-2">
                {(() => {
                  const Icon = iconMap[activeCategory.icon] || Settings;
                  return <Icon className="w-6 h-6 text-[#cba6f7]" />;
                })()}
                <h2 className="text-2xl font-bold text-[#cdd6f4]">{activeCategory.name}</h2>
              </div>
              <p className="text-[#a6adc8] text-sm">{activeCategory.description}</p>
            </div>

            {/* Preferences List */}
            <div className="space-y-3">
              <AnimatePresence mode="popLayout">
                {filteredPreferences.map((pref, index) => (
                  <motion.div
                    key={pref.id}
                    layout
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -10 }}
                    transition={{ delay: index * 0.02 }}
                    className={`rounded-xl border transition-all ${
                      selections[pref.id]
                        ? 'bg-[#313244]/80 border-[#a6e3a1]/30'
                        : 'bg-[#313244]/40 border-[#45475a]/50'
                    }`}
                  >
                    <div className="p-4">
                      <div className="flex items-start gap-3">
                        {/* Toggle */}
                        <motion.button
                          whileTap={{ scale: 0.9 }}
                          onClick={() => togglePreference(pref.id)}
                          className={`mt-0.5 flex-shrink-0 w-11 h-6 rounded-full transition-all relative ${
                            selections[pref.id]
                              ? 'bg-[#a6e3a1]'
                              : 'bg-[#45475a]'
                          }`}
                        >
                          <motion.div
                            layout
                            className="absolute top-1 w-4 h-4 rounded-full bg-white shadow-sm"
                            animate={{
                              x: selections[pref.id] ? 22 : 4,
                            }}
                            transition={{ type: 'spring', stiffness: 500, damping: 30 }}
                          />
                        </motion.button>

                        {/* Content */}
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 flex-wrap">
                            <h3 className="text-sm font-semibold text-[#cdd6f4]">{pref.name}</h3>
                            {pref.risk === 'high' && (
                              <span className="px-1.5 py-0.5 rounded text-[10px] font-medium bg-[#f38ba8]/20 text-[#f38ba8] border border-[#f38ba8]/30">
                                HIGH RISK
                              </span>
                            )}
                            {pref.risk === 'medium' && (
                              <span className="px-1.5 py-0.5 rounded text-[10px] font-medium bg-[#fab387]/20 text-[#fab387] border border-[#fab387]/30">
                                MEDIUM
                              </span>
                            )}
                            {pref.recommended && (
                              <span className="px-1.5 py-0.5 rounded text-[10px] font-medium bg-[#a6e3a1]/20 text-[#a6e3a1] border border-[#a6e3a1]/30">
                                RECOMMENDED
                              </span>
                            )}
                            <span className="px-1.5 py-0.5 rounded text-[10px] font-medium bg-[#89b4fa]/20 text-[#89b4fa] border border-[#89b4fa]/30">
                              {pref.source === 'both' ? 'BF + AF' : pref.source === 'betterfox' ? 'Betterfox' : 'arkenfox'}
                            </span>
                          </div>
                          <p className="text-xs text-[#a6adc8] mt-1">{pref.description}</p>
                          
                          {/* Expandable details */}
                          <motion.button
                            onClick={() => toggleExpand(pref.id)}
                            className="mt-2 flex items-center gap-1 text-[10px] text-[#6c7086] hover:text-[#a6adc8] transition-colors"
                          >
                            <Info className="w-3 h-3" />
                            <span>{expandedPrefs.has(pref.id) ? 'Hide' : 'Show'} technical details</span>
                            <motion.span
                              animate={{ rotate: expandedPrefs.has(pref.id) ? 90 : 0 }}
                            >
                              <ChevronRight className="w-3 h-3" />
                            </motion.span>
                          </motion.button>

                          <AnimatePresence>
                            {expandedPrefs.has(pref.id) && (
                              <motion.div
                                initial={{ height: 0, opacity: 0 }}
                                animate={{ height: 'auto', opacity: 1 }}
                                exit={{ height: 0, opacity: 0 }}
                                className="overflow-hidden"
                              >
                                <div className="mt-2 p-3 rounded-lg bg-[#1e1e2e] border border-[#45475a]">
                                  <div className="space-y-1.5 text-xs">
                                    <div className="flex items-center gap-2">
                                      <span className="text-[#6c7086]">Key:</span>
                                      <code className="text-[#f9e2af] font-mono text-[11px]">{pref.key}</code>
                                    </div>
                                    <div className="flex items-center gap-2">
                                      <span className="text-[#6c7086]">Type:</span>
                                      <code className="text-[#89dceb] font-mono">{pref.type}</code>
                                    </div>
                                    <div className="flex items-center gap-2">
                                      <span className="text-[#6c7086]">Value:</span>
                                      <code className="text-[#a6e3a1] font-mono">
                                        {typeof pref.defaultValue === 'string' ? `"${pref.defaultValue}"` : String(pref.defaultValue)}
                                      </code>
                                    </div>
                                    <div className="flex items-center gap-2">
                                      <span className="text-[#6c7086]">Section:</span>
                                      <span className="text-[#cdd6f4]">{pref.section}</span>
                                    </div>
                                  </div>
                                </div>
                              </motion.div>
                            )}
                          </AnimatePresence>
                        </div>
                      </div>
                    </div>
                  </motion.div>
                ))}
              </AnimatePresence>

              {filteredPreferences.length === 0 && (
                <div className="text-center py-12 text-[#6c7086]">
                  <AlertTriangle className="w-8 h-8 mx-auto mb-3 opacity-50" />
                  <p>No preferences match your search.</p>
                </div>
              )}
            </div>
          </motion.div>
        </div>

        {/* Bottom Action Bar */}
        <motion.div
          initial={{ y: 20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ delay: 0.5 }}
          className="fixed bottom-0 left-0 right-0 z-50 backdrop-blur-xl bg-[#1e1e2e]/90 border-t border-[#313244]"
        >
          <div className="max-w-7xl mx-auto px-4 sm:px-6 py-4">
            <div className="flex items-center justify-between gap-4">
              <div className="flex items-center gap-3">
                <div className="text-sm text-[#a6adc8]">
                  <span className="text-[#a6e3a1] font-bold">{selectedCount}</span> preferences selected
                </div>
              </div>
              <div className="flex items-center gap-3">
                <motion.button
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  onClick={() => setShowPreview(!showPreview)}
                  className="px-4 py-2.5 rounded-xl bg-[#313244] border border-[#45475a] text-[#cdd6f4] text-sm font-medium hover:bg-[#45475a] transition-colors"
                >
                  {showPreview ? 'Hide Preview' : 'Preview user.js'}
                </motion.button>
                <motion.button
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  onClick={copyToClipboard}
                  className="px-4 py-2.5 rounded-xl bg-[#89b4fa]/10 border border-[#89b4fa]/30 text-[#89b4fa] text-sm font-medium hover:bg-[#89b4fa]/20 transition-colors flex items-center gap-2"
                >
                  {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                  {copied ? 'Copied!' : 'Copy'}
                </motion.button>
                <motion.button
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  onClick={downloadFile}
                  className="px-4 py-2.5 rounded-xl bg-gradient-to-r from-[#cba6f7] to-[#f38ba8] text-[#1e1e2e] text-sm font-bold hover:opacity-90 transition-opacity flex items-center gap-2"
                >
                  <Download className="w-4 h-4" />
                  Download user.js
                </motion.button>
              </div>
            </div>
          </div>
        </motion.div>

        {/* Preview Panel */}
        <AnimatePresence>
          {showPreview && (
            <motion.div
              initial={{ opacity: 0, y: 50 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: 50 }}
              className="fixed inset-0 z-40 flex items-end justify-center p-4 pb-24"
            >
              <div className="absolute inset-0 bg-black/50 backdrop-blur-sm" onClick={() => setShowPreview(false)} />
              <motion.div
                initial={{ scale: 0.95 }}
                animate={{ scale: 1 }}
                exit={{ scale: 0.95 }}
                className="relative w-full max-w-4xl max-h-[70vh] rounded-2xl bg-[#1e1e2e] border border-[#313244] overflow-hidden shadow-2xl"
              >
                <div className="flex items-center justify-between px-6 py-4 border-b border-[#313244]">
                  <h3 className="text-lg font-bold text-[#cdd6f4]">user.js Preview</h3>
                  <button
                    onClick={() => setShowPreview(false)}
                    className="p-1 rounded-lg hover:bg-[#313244] transition-colors text-[#a6adc8]"
                  >
                    ✕
                  </button>
                </div>
                <div className="overflow-auto max-h-[calc(70vh-60px)] p-6">
                  <pre className="text-xs font-mono text-[#a6adc8] whitespace-pre-wrap leading-relaxed">
                    {generateUserJs()}
                  </pre>
                </div>
              </motion.div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Bottom padding for fixed bar */}
        <div className="h-24" />
      </div>
    </div>
  );
}

export default App;
